name: NB Next customisations
on: [push, pull_request]
jobs:
  apply-old-patches:
    runs-on: ubuntu-latest
    env:
      PATCH_DIR: customisation/patches/${{github.event.repository.name}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout customisations
        uses: actions/checkout@v3
        with:
          repository: thenbdev/Customisations
          path: customisation

      - name: Apply patches
        # if: hashFiles('$PATCH_DIR')!=''  #TODO: why is this not working
        run: |
        
          # Check if the patch directory exists
          [ -d "$PATCH_DIR" ] || { echo "Patch directory $PATCH_DIR not found."; exit 0; }

          for patch in "$PATCH_DIR"*.patch; do
            if [[ -f "$patch" ]]; then
              if git log --grep="$(basename "${patch%.*}")" -1 > /dev/null; then
                echo "Patch $(basename "${patch%.*}") has already been applied, skipping"
              else
                git apply --reject --whitespace=fix "$patch" || exit 1
                echo "Applied patch $(basename "${patch%.*}")"
              fi
            fi
          done

      - name: Cleanup
        run: rm -rf customisation
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4


  replacements:
    needs: apply-old-patches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find and Replace links (direct/docs, youtube)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: (erpnext.com|www.youtube.com)
          replace: "nbnextlinks"
          regex: true


      - name: Find and Replace name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: (ERP Next|ERPNext)
          replace: "NB Next"
          regex: true


      # TODO: change the download/logo location to customsation repo
      - name: Find and Replace logo
        if: ${{ hashFiles('**/erpnext-logo.*') }}
        # TODO: figure out where is the file and replace it. currently static handling
        run: |
          cd erpnext/public/images
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-logo.svg
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-logo.png
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-favicon.svg


      - name: Restore unwanted changes
        run: |
          git status
          git restore --source=HEAD --staged --worktree -- .github
          git status

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
