name: NB Next customisations
on: [push, pull_request]
jobs:
  apply-old-patches:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout customisations
        uses: actions/checkout@v3
        with:
          repository: thenbdev/Customisations
          path: customisation

      # TODO: Apply patches given the repo (frappe/erpnext/hrms/payments/etc...)
      - name: Apply patches
        run: |
          ls
          pwd
          ls ..
          # Loop through repo
          cd customisation/


          # Specify the directory containing the git patches
          PATCH_DIR="customisation/patches/${{github.event.repository.name}}"

          # Check if the patch directory exists
          [ -d "$PATCH_DIR" ] || { echo "Patch directory $PATCH_DIR not found."; exit 0; }

          # Change to the directory containing the git patches
          cd "$PATCH_DIR" || { echo "Cannot change to directory $PATCH_DIR"; exit 1; }

          # Loop through all the patch files in numeric order and apply them
          for PATCH_FILE in $(ls -v *.patch)
          do
            # Check if the patch has already been applied
            if git log -1 --grep="$PATCH_FILE" >/dev/null 2>&1; then
              echo "Patch $PATCH_FILE has already been applied. Skipping..."
            elif git apply --check "$PATCH_FILE"; then
              echo "Applying patch $PATCH_FILE..."
              git apply "$PATCH_FILE" || { echo "Error applying patch $PATCH_FILE"; exit 1; }
            else
              echo "Cannot apply patch $PATCH_FILE. Please resolve conflicts manually."
              exit 1
            fi
          done

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4


  replacements:
    needs: apply-old-patches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find and Replace links (direct/docs, youtube)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: (erpnext.com|www.youtube.com)
          replace: "nbnextlinks"
          regex: true


      - name: Find and Replace name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: (ERP Next|ERPNext)
          replace: "NB Next"
          regex: true


      # TODO: change the download/logo location to customsation repo
      - name: Find and Replace logo
        if: ${{ hashFiles('**/erpnext-logo.*') }}
        # TODO: figure out where is the file and replace it. currently static handling
        run: |
          cd erpnext/public/images
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-logo.svg
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-logo.png
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-favicon.svg


      - name: Restore unwanted changes
        run: |
          git status
          git restore --source=HEAD --staged --worktree -- .github
          git status

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
